image: golang:latest

variables:
  REPO_NAME: $CI_SERVER_HOST/$CI_PROJECT_PATH
  GIT_CLONE_PATH: /builds/go/src/$REPO_NAME/
  GOPATH: /builds/go

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)

vet:
  stage: test
  script:
    - go vet $(go list ./... | grep -v /vendor/)

unit-tests:
  stage: test
  script:
    - go test -race $(go list ./... | grep -v /vendor/)
